### ISSUE TITLE
Problem with counterfeit packages

### ISSUE THREAD

**Issue by petermakeswebsites** [victorperin/is-is-is-odd#2]
Hi there,

I am having some issues. I feel that this plugin is "easy to fake".  I was wondering if there was a solution to possibly create some way of verifying whether this plugin is the legitimate version?

Thank you,
Pete

**Comment by algj** [comment]
I think [is-is-is-is-is-odd](https://github.com/algiuxass/is-is-is-is-is-odd) might be a good solution, sadly npm detects this as spam.

**Comment by petermakeswebsites** [comment]
I fail to see how someone thinks it's spam, it's a very useful tool. Anyway, thanks for pointing that out.
